openapi: '3.0.2'
info:
  title: Linkedin API
  version: '1.0'


paths:
  /createprofile:
    put:
      description: "create profile"
      operationId: createprofile
      responses:
        '200':
          description: OK
  /getprofile:
    get:
      description: "get profile"
      operationId: getprofile
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                example:
                  linkedInProfile:
                    username: user1
                    email: user1@foo.com
  /getname:
    get:
      description: "get name"
      operationId: getname
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                example:
                  linkedInProfile:
                    first_name: jane
                    last_name: fonda

